---
title: "Central Limit Theorem Practice Problems"
author: "Leandro Ledesma"
date: "2024-03-02"
output: html_document
---

The following questions are from Chapter 5: Four Fundamental Concepts in Statistics Unplugged (4th edition) by Sally Cadwell.

### Part 1: Questions

1) In a random sample, every unit in the population has a(n) ______ chance of being selected?

2) In a random sample, the selection of any one unit ______ affec the selection of any other unit.

3) In a random sample, ________ combinations are possible.

4) When selection a sample, the physical representation of the population is known as the ______

5) A representative sample is one in which important characteristics in the population are mirrored in the ______

6) The difference between a sample statistic and a population parameter that is due to chance is referred to as _______

7) The mean of a population ($\mu$) = 54.72, and the mean of a sample from the population ($\overline{X}$) = 54.92. Assuming the difference between the two values is due to chance, we can refer to the difference as sampling _______.

8) A sampling distribution of sample means is based on taking repeated samples (of size n) from the same population and plotting the _______ of the difference samples. 

9) According to the Central Limit Theorem, the mean of a sampling distribution of sample means will equal the _______ of a population from which the samples were drawn.

10) The standard deviation of a sampling distribution of sample means is referred to as the _______.

11) According to the Central Limit Theorem, and given a sampling distribution of sample means, the standard error of the mean will equal the _______ of the population divided by the _______ of the sample size.

12) The shape of a sampling distribution of sample means will approach the sahpe of a ________ curve.

### Part 2: Application Questions 

1. A population has a mean ($\mu$) of 24.12 and a standard deviation ($\sigma$) of 4. Assume that a sampling distribution of sample means has been con- structed, based on repeated samples of n = 100 from this population.
a. What would be the value of the mean of the sampling distribution?
b. What would be the value of the standard error of the mean?

2. A population has a mean ($\mu$) of 30 and a standard deviation ($\sigma$) of 6. Assume that a sampling distribution of sample means has been constructed, based on repeated samples of n = 225 from this population. 
a. What would be the value of the mean of the sampling distribution?
b. What would be the value of the standard error of the mean?

3. A population has a mean ($\mu$) of 120 and a standard deviation ($\sigma$) of 30. Assume that a sampling distribution of sample means has been constructed, based on repeated samples of n = 100 from this population. 
a. What would be the value of the mean of the sampling distribution?
b. What would be the value of the standard error of the mean?

4. A population has a mean ($\mu$) of 615 and a standard deviation ($\sigma$) of 90. Assume that a sampling distribution of sample means has been constructed, based on repeated samples of n = 400 from this population. 
a. What would be the value of the mean of the sampling distribution?
b. What would be the value of the standard error of the mean?

5. A population has a mean ($\mu$) of 55 and a standard deviation ($\sigma$) of 17. Assume that a sampling distribution of sample means has been constructed, based on repeated samples of n = 100 from this population. 
a. What would be the value of the mean of the sampling distribution?
b. What would be the value of the standard error of the mean?




