---
title: "MegaGrant Data Overview"
output:
  html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

This document serves to track data cleaning for MegaGrant data. For context, this was a study that took place in Russia that investigated how rearing in an institutionalized environment reflected behaviorally and neurophysiolologically in adulthood. Several different measures were collected from participants including: demographic information, medical records, IQ, executive function, quality of life, delinquency, language abilities, and EEG data. 

For my master's thesis, I am curious to investigate if language related measures are associated with neurophysiological measures, specifically with power of certain frequency bands in resting-state EEG (rsEEG). 


### Data Cleaning

**Step 1**: The Master Excel sheet that contained all of the ID's from the study and the data that was associated to it needed to be cleaned. After cleaning the final likely ID number for this study is 700. [[Click here to view script]](https://leoledesma237.github.io/LeoWebsite/MegaGrant.Scripts/ID.Cleaning.html) 

**Step 2**: Now that we know our sample size, we need to investigate how many subjects contain data for the variables we are interested. Our predictor will be spelling capabilities (ARFA) and the our outcome is rsEEG. Additionally, we want to control for Sex, Age, Group, and IQ. From our 700 ID's, 604 have these data present. [[Click here to view script]](https://leoledesma237.github.io/LeoWebsite/MegaGrant.Scripts/Ideal.data.html)

**Step 3**: As mentioned in step 2, even though we identified our ideal N for our analysis, this would only be possible if all rsEEG recordings had no issues throughout the preprocessing pipeline. From our initial 604 rsEEG files, 466 made it through the preprocessing stage. [[Click  here to view script]](https://leoledesma237.github.io/LeoWebsite/MegaGrant.Scripts/Verify.rsEEG.html)

**Step 4**: Now that we have our cleaned rsEEG files, we need to process them using Fast Fourier transform to convert them into the frequency domain from the time domain. This process was done using MATLAB scripts. This Rmarkdown will now be showing that process but instead cleaning the outputs created from FFT. The outputs from this are two dataset. Both have the average power for the 5 frequency bands for each of the 462 subjects, however, one includes topographical information and the other does not. [[Click here to view the script]](https://leoledesma237.github.io/LeoWebsite/MegaGrant.Scripts/Frequency.Band.Scoring.html)

**Step 5**: Now we need to walk through the process of cleaning and scoring our main predictor variable, which is spelling performance. [[Click here to view script]](https://leoledesma237.github.io/LeoWebsite/MegaGrant.Scripts/ARFA.Scoring.html) 

**Step 6**: Scoring CFIT data. Initially we were given IQ scores from the CFIT Scale 2 Form-B that was used in this study. Unfortunately, this version of the CFIT cannot be used to get an IQ score, because there is no way to standardized the scores. Thus, we will need to take the raw data and calculate a raw score for each subject. [[Click here to view script]](https://leoledesma237.github.io/LeoWebsite/MegaGrant.Scripts/CFIT.Scoring.html)


### Data Analysis

**rsEEG and Spelling Performance Analysis** <add description here> (https://leoledesma237.github.io/LeoWebsite/MegaGrant.Scripts/Analyzing.rsEEG.Spelling.html)


