---
title: "Individual Differences in Response to Stress Study Overview"
output:
  html_document

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
``` 


This document serves to track data cleaning for the Individual Differences in Response to Stress: Behavioral and Neurophysiological Correlates study. However, that name is a mouthful and most members in the lab know it as the study for the Office of Naval Research (ONR). Thus, the rest of this document will refer to this study and its data as ONR (I must specify that we are not a part of ONR in anyway- we are just collaborating with them).

This study is investigating how different stressors (intense exercise and sleep deprivation) influence cognitive performance in virtual reality (VR). We are predominantly interested in their effects on inhibition and working memory. To measure these constructs, we developed a Go/No-Go (GnG) and Nback paradigm in VR that is compatible with EEG recordings. This will allow us to not only capture their behavioral performance in these tasks but also reveal brain activity that is associated with the behavior (Special thanks to Hechmi Kilani and Devante Williams for designing these paradigms). There are other data collected for the ONR study including: physiological measures (heart rate, blood oxygen saturation, breathing rate), hormone levels, epigenetics, language capabilities, and more. This document will solely focus on the behavioral data from the GnG and Nback, and their EEG.

### Data Cleaning

**Step 1**: CSV files for each tasks were saved on different computers and named oddly. The purpose of this script was to label the testing session to each CSV file and combine all GnG and N-back files into two CSV files. We have at least on CSV file from 200 participants and 119 have completed all testing days. [[Click here to view script]](https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/Day.Labeling.html)

**Step 2**: Including demographic information [[Click here to view script]](https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/Adding.Demographics.html)

**Step 3**: GnG EEG data Preprocessing [[Click here to view script]](https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/GnG.Preprocessing.Pipeline.html)


### Data Scoring

**BRIEF** <add description here>(https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/BRIEF.Scoring.html)

**VR Behavioral** <add description here>(https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/VR.Behavioral.Scoring.html)

**CFIT** <add description here>(https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/CFIT.Scoring.html)


### Data Analysis

**Validating VR Performance with the BRIEF** <add description here>(https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/Analyzing.BRIEF.VR.Behavior.html)

**CFIT and Nback analysis** <add description here>(https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/Analyzing.CFIT.Nback.html)

**Color influence in Color Saber Match GnG** <add description here>(https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/Analyzing.Color.GnG.html)

**GnG EEG N2** <add description here>(https://leoledesma237.github.io/LeoWebsite/ONR.Scripts/Analyzing.GnG.N2.html)
