---
title: "Data Scoring BMI"
author: "Leandro Ledesma"
date: "2024-03-26"
output: html_document
---

### Load in the data manipulation packages first

```{r loading in the packages, warning = FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(readxl)
library(kableExtra)

```

### Load in the data

```{r load in the data, warning = FALSE}
# Set working directory
setwd("Z:/eglab/A_ALL Project Data/Zambia projects (R01, R21, OVC)/ZambiaOVC_2022/ZambiaOVC_CleanFiles/Cohort1_cleaned_July2021_forNan/C1T1")

# Load in the data
Physical1 <- read_excel("PhysicalData_Zambia_01Aug09_coh1_tm1_clean.xlsx")

# Set working directory
setwd("Z:/eglab/A_ALL Project Data/Zambia projects (R01, R21, OVC)/ZambiaOVC_2022/ZambiaOVC_CleanFiles/Cohort2_cleanedJun2021_forNan/C2T1")

# Load in the data
Physical2 <- read_excel("PhysicalData_Zambia_01Aug09_coh2_tm1_clean.xlsx")

# Set working directory
setwd("Z:/eglab/A_ALL Project Data/Zambia projects (R01, R21, OVC)/ZambiaOVC_2022/ZambiaOVC_CleanFiles/Cohort3_cleaned_Jul2021_forNan/C3T1")

# Load in the data
Physical3 <- read_excel("ZambiaOVC_PhysicalData_01Aug09_coh3_tm1.xlsx")

```


### Bind all of the Physical together

```{r bind the datasets}
# Extract the variables of interest from each dataset
Physical1.sub <-  
Physical1 %>%
  select(OVC_ID, 
         HEIGHT_cm,
         WEIGHT_kg,
         Head_Circum_cm)

# Assume that 1 means boy
Physical2.sub <-  
Physical2 %>%
  select(OVC_ID = OVCID, 
         HEIGHT_cm = HEIGHT,
         WEIGHT_kg = WEIGHT,
         Head_Circum_cm = Head_Circum)

Physical3.sub <-  
Physical3 %>%
  select(OVC_ID, 
         HEIGHT_cm = HEIGHT,
         WEIGHT_kg = WEIGHT,
         Head_Circum_cm = Head_Circum)


# Bind them together
Physical <- 
  Physical1.sub %>%
  rbind(Physical2.sub) %>%
  rbind(Physical3.sub)
```

### Calculate BMI

BMI in Sophie's paper is define as weight (in kg) divided by their height in meters squared: w/h^2

```{r scoring the data}
# Score for all the rows
Physical <- Physical %>%
  mutate(Height_m = HEIGHT_cm / 100,
         Height_m_sqrd = Height_m^2,
         BMI = round(WEIGHT_kg/Height_m_sqrd),2)


```

### Save the data

```{r save the data}
# Set the working directory
setwd("~/OVC/Physical Data")

# Save the data
write_csv(Physical, "Physical.scored.csv")

```
