---
title: "Data Scoring ZAT Reading Comprehension"
author: "Leandro Ledesma"
date: "2024-04-02"
output: html_document
---
### Load in the data manipulation packages first

```{r loading in the packages, warning = FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(readxl)
library(kableExtra)

```

### Load in the data

```{r load in the data, warning = FALSE}
# Set working directory
setwd("Z:/eglab/A_ALL Project Data/Zambia projects (R01, R21, OVC)/ZambiaOVC_2022/ZambiaOVC_CleanFiles/Cohort1_cleaned_July2021_forNan/C1T1")

# Load in the data
ZAT1 <- read_excel("ZambiaOVC_ZATRR_PWWR_RC_M_co1_tm1_clean.xlsx")

# Set working directory
setwd("Z:/eglab/A_ALL Project Data/Zambia projects (R01, R21, OVC)/ZambiaOVC_2022/ZambiaOVC_CleanFiles/Cohort2_cleanedJun2021_forNan/C2T1")

# Load in the data
ZAT2 <- read_excel("ZambiaOVC_ZATRR_PWWR_RC_M_coh2_tm1_clean.xlsx")

# Set working directory
setwd("Z:/eglab/A_ALL Project Data/Zambia projects (R01, R21, OVC)/ZambiaOVC_2022/ZambiaOVC_CleanFiles/Cohort3_cleaned_Jul2021_forNan/C3T1")

# Load in the data
ZAT3 <- read_excel("ZambiaOVC_ZATRR_PWWR_RC_M_coh3_tm1_clean.xlsx")

```

### Bind all of the ZAT reading together

```{r bind the datasets}
# Extract the variables of interest from each dataset
ZAT1.RC <-  
ZAT1 %>%
    select(OVC_ID, 
         contains("RC"))

# Assume that 1 means boy
ZAT2.RC <- 
ZAT2 %>%
  select(OVC_ID, 
         contains("RC"),
         - Ch_sex_F1_M0)

ZAT3.RC <- 
ZAT3 %>%
   select(OVC_ID, 
         contains("RC"))


# Bind them together
ZAT.RC <- 
  ZAT1.RC %>%
  rbind(ZAT2.RC) %>%
  rbind(ZAT3.RC)


```


### Score the ZAT Math

Each value that is not 1 is essentially a 0.

```{r scoring the data}
# Set the working directory
setwd("C:/Users/lledesma.TIMES/Documents/OVC/Scoring Book")

# Load in scoreing book
ZAT.RC.scoring.uncleaned <- read_excel("OVC_CodeBook.xlsx", sheet = "ZAT_RC")

# clean it up a bit
ZAT.RC.answers <- ZAT.RC.scoring.uncleaned %>%
  select(`OVC Project`, Correct.Response = `Correct response...10`)  %>% 
  filter(complete.cases(.))

# Some data cleaning on the ZAT
ZAT.RC <- ZAT.RC %>%
  mutate_all(., function(x) as.numeric(x))

# Convert ZAT Math to long format
ZAT.RC.long <- ZAT.RC %>%
  pivot_longer(-OVC_ID)

# Introduce the correct answers
ZAT.RC.long$Correct.Response <- rep(ZAT.RC.answers$Correct.Response, nrow(ZAT.RC.long)/25)

# Score each item 
ZAT.RC.long <- ZAT.RC.long %>%
  mutate(Score = ifelse(value == Correct.Response, 1, 0))

# Remove practice trials
ZAT.RC.long <- ZAT.RC.long %>% 
  filter(!(name %in% c("RCT1","RCT2","RCT5","RCT6")))

# Obtain a raw math score per person
ZAT.RC.final <- ZAT.RC.long %>%
  group_by(OVC_ID) %>%
  summarize(RC.Score = sum(Score, na.rm = TRUE))

```


### Save the data

```{r save the data}
# Set the working directory
setwd("~/OVC/ZAT")

# Save the data
write_csv(ZAT.RC.final, "ZAT.RC.scored.csv")

```